name: ClaudeCode

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - feature/**

jobs:
  claudecode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthropic/claude-code-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
